using System.Collections.Generic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace TrainSim.SceneBuilding
{
    /// <summary>
    /// Editor helpers for the train sim.
    ///
    /// Both scenes are generated by Tools/generate_scenes.py, which builds them from his
    /// SampleScene so the lighting, skybox, rails and signal are his by construction. This file
    /// deliberately does not build scenes any more: two builders would drift apart, and the one
    /// that used to live here produced scene 2 from the asset pack demo scene, which is where
    /// the fog and the broken purple sky came from.
    ///
    /// What is left is the measuring and navigation that is genuinely easier inside Unity.
    /// </summary>
    public static class TrainSimTools
    {
        const string Scene1Path = "Assets/Scenes/SampleScene.unity";
        const string Scene2Path = "Assets/Scenes/Scene2_StationBoarding.unity";

        const string TrainPrefabPath =
            "Assets/Polyeler/Simple Train Pack/Prefabs/Train/Train_Type A.prefab";

        const string RailPrefabPath =
            "Assets/Polyeler/Simple Train Pack/Prefabs/Rail/Straight rail.prefab";

        const string PassengerPrefabPath =
            "Assets/pixel horror abandoned rural  train station/Models/Hitogatas.fbx";

        const string StationScenePath =
            "Assets/pixel horror abandoned rural  train station/Scenes/environment with station.unity";

        // ==========================================
        // NAVIGATION
        // ==========================================

        [MenuItem("Tools/Train Sim/Open Scene 1", priority = 0)]
        public static void OpenScene1()
        {
            EditorSceneManager.OpenScene(Scene1Path, OpenSceneMode.Single);
            Debug.Log("[TRAIN SIM] Opened " + Scene1Path);
        }

        [MenuItem("Tools/Train Sim/Open Scene 2", priority = 1)]
        public static void OpenScene2()
        {
            EditorSceneManager.OpenScene(Scene2Path, OpenSceneMode.Single);
            Debug.Log("[TRAIN SIM] Opened " + Scene2Path);
        }

        /// <summary>
        /// Loads scene 1 with scene 2 alongside it for comparing the two. Scene 1 stays active,
        /// so pressing Play still starts the run in.
        /// </summary>
        [MenuItem("Tools/Train Sim/Open Both Scenes", priority = 2)]
        public static void OpenBothScenes()
        {
            Scene one = EditorSceneManager.OpenScene(Scene1Path, OpenSceneMode.Single);
            EditorSceneManager.OpenScene(Scene2Path, OpenSceneMode.Additive);
            SceneManager.SetActiveScene(one);

            Debug.Log(
                "[TRAIN SIM] Both scenes loaded. Scene 1 is active, so Play starts the run in."
            );
        }

        [MenuItem("Tools/Train Sim/Add Scenes To Build Settings", priority = 3)]
        public static void AddScenesToBuildSettings()
        {
            var wanted = new List<EditorBuildSettingsScene>
            {
                new EditorBuildSettingsScene(Scene1Path, true),
                new EditorBuildSettingsScene(Scene2Path, true)
            };

            foreach (var existing in EditorBuildSettings.scenes)
            {
                if (existing.path != Scene1Path &&
                    existing.path != Scene2Path)
                {
                    wanted.Add(existing);
                }
            }

            EditorBuildSettings.scenes = wanted.ToArray();

            Debug.Log("[TRAIN SIM] Scene list now holds " + wanted.Count + " scenes.");
        }

        // ==========================================
        // MEASURING
        // ==========================================

        /// <summary>
        /// Prints the real mesh bounds behind the numbers at the top of the generator. Run this
        /// when something looks like it is floating or sunk, then correct the constants in
        /// Tools/generate_scenes.py rather than dragging objects around.
        /// </summary>
        [MenuItem("Tools/Train Sim/Probe Layout", priority = 20)]
        public static void Probe()
        {
            var sb = new System.Text.StringBuilder();
            sb.AppendLine("===== LAYOUT PROBE =====");

            ProbePrefab(sb, TrainPrefabPath);
            ProbePrefab(sb, RailPrefabPath);
            ProbePrefab(sb, PassengerPrefabPath);

            ProbeTerrainAndPlatforms(sb);

            Debug.Log(sb.ToString());
        }

        static void ProbePrefab(System.Text.StringBuilder sb, string path)
        {
            GameObject prefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);

            if (prefab == null)
            {
                sb.AppendLine("MISSING: " + path);
                return;
            }

            GameObject instance = (GameObject)PrefabUtility.InstantiatePrefab(prefab);
            instance.transform.position = Vector3.zero;
            instance.transform.rotation = Quaternion.identity;

            Bounds bounds = new Bounds(Vector3.zero, Vector3.zero);
            bool first = true;

            foreach (Renderer renderer in instance.GetComponentsInChildren<Renderer>())
            {
                if (first)
                {
                    bounds = renderer.bounds;
                    first = false;
                }
                else
                {
                    bounds.Encapsulate(renderer.bounds);
                }
            }

            sb.AppendLine(System.IO.Path.GetFileNameWithoutExtension(path));
            sb.AppendLine("   size " + bounds.size + "   min " + bounds.min + "   max " + bounds.max);

            Object.DestroyImmediate(instance);
        }

        /// <summary>
        /// The terrain extent matters: the train starts at z = -95 and must not run off the edge
        /// of the ground. Platform surface height decides where the passengers stand.
        /// </summary>
        static void ProbeTerrainAndPlatforms(System.Text.StringBuilder sb)
        {
            Scene scene = EditorSceneManager.OpenScene(StationScenePath, OpenSceneMode.Additive);

            float platformTop = float.MinValue;

            foreach (GameObject root in scene.GetRootGameObjects())
            {
                Terrain terrain = root.GetComponent<Terrain>();

                if (terrain != null && terrain.terrainData != null)
                {
                    Vector3 size = terrain.terrainData.size;
                    Vector3 origin = root.transform.position;

                    sb.AppendLine("Terrain at " + origin + " size " + size);
                    sb.AppendLine("   covers x " + origin.x + " to " + (origin.x + size.x));
                    sb.AppendLine("   covers z " + origin.z + " to " + (origin.z + size.z));
                }

                if (!root.name.StartsWith("cement platform"))
                {
                    continue;
                }

                foreach (Renderer renderer in root.GetComponentsInChildren<Renderer>())
                {
                    // The west platform is the one the passengers board from.
                    if (renderer.bounds.center.x < 0f &&
                        renderer.bounds.max.y > platformTop)
                    {
                        platformTop = renderer.bounds.max.y;
                    }
                }
            }

            sb.AppendLine("west platform surface y = " + platformTop);

            EditorSceneManager.CloseScene(scene, true);
        }
    }
}
