using System.Collections.Generic;
using UnityEditor;
using System.IO;
using UnityEditor.Animations;
using UnityEditor.Build.Reporting;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace TrainSim.SceneBuilding
{
    /// <summary>
    /// Editor helpers for the train sim.
    ///
    /// Both scenes are generated by Tools/generate_scenes.py, which builds them from his
    /// SampleScene so the lighting, skybox, rails and signal are his by construction. This file
    /// deliberately does not build scenes any more: two builders would drift apart, and the one
    /// that used to live here produced scene 2 from the asset pack demo scene, which is where
    /// the fog and the broken purple sky came from.
    ///
    /// What is left is the measuring and navigation that is genuinely easier inside Unity.
    /// </summary>
    public static class TrainSimTools
    {
        const string Scene1Path = "Assets/Scenes/SampleScene.unity";
        const string Scene2Path = "Assets/Scenes/Scene2_StationBoarding.unity";
        const string Scene3Path = "Assets/Scenes/Scene3_Crossover.unity";

        const string TrainPrefabPath =
            "Assets/Polyeler/Simple Train Pack/Prefabs/Train/Train_Type A.prefab";

        const string RailPrefabPath =
            "Assets/Polyeler/Simple Train Pack/Prefabs/Rail/Straight rail.prefab";

        const string HitogatasModelPath =
            "Assets/pixel horror abandoned rural  train station/Models/Hitogatas.fbx";

        const string StationScenePath =
            "Assets/pixel horror abandoned rural  train station/Scenes/environment with station.unity";

        // ==========================================
        // NAVIGATION
        // ==========================================

        [MenuItem("Tools/Train Sim/Open Scene 1", priority = 0)]
        public static void OpenScene1()
        {
            EditorSceneManager.OpenScene(Scene1Path, OpenSceneMode.Single);
            Debug.Log("[TRAIN SIM] Opened " + Scene1Path);
        }

        [MenuItem("Tools/Train Sim/Open Scene 2", priority = 1)]
        public static void OpenScene2()
        {
            EditorSceneManager.OpenScene(Scene2Path, OpenSceneMode.Single);
            Debug.Log("[TRAIN SIM] Opened " + Scene2Path);
        }

        [MenuItem("Tools/Train Sim/Open Scene 3", priority = 2)]
        public static void OpenScene3()
        {
            EditorSceneManager.OpenScene(Scene3Path, OpenSceneMode.Single);
            Debug.Log("[TRAIN SIM] Opened " + Scene3Path);
        }

        /// <summary>
        /// Loads scene 1 with scene 2 alongside it, for comparing the two in the editor.
        ///
        /// Do not press Play with both loaded. Each scene carries its own train, signals and
        /// station, and scene 2 opens on an enabled station camera, so that camera renders over
        /// scene 1 and the run in is not what you see. Play scene 1 on its own: it loads scene 2
        /// itself when the train settles.
        /// </summary>
        [MenuItem("Tools/Train Sim/Open Both Scenes (inspect only)", priority = 2)]
        public static void OpenBothScenes()
        {
            Scene one = EditorSceneManager.OpenScene(Scene1Path, OpenSceneMode.Single);
            EditorSceneManager.OpenScene(Scene2Path, OpenSceneMode.Additive);
            SceneManager.SetActiveScene(one);

            Debug.LogWarning(
                "[TRAIN SIM] Both scenes loaded for inspection. Do NOT press Play like this - " +
                "scene 2 opens on an enabled station camera which renders over scene 1. " +
                "Use Open Scene 1 to play the sequence."
            );
        }

        [MenuItem("Tools/Train Sim/Add Scenes To Build Settings", priority = 3)]
        public static void AddScenesToBuildSettings()
        {
            var wanted = new List<EditorBuildSettingsScene>
            {
                new EditorBuildSettingsScene(Scene1Path, true),
                new EditorBuildSettingsScene(Scene2Path, true),
                new EditorBuildSettingsScene(Scene3Path, true)
            };

            foreach (var existing in EditorBuildSettings.scenes)
            {
                if (existing.path != Scene1Path &&
                    existing.path != Scene2Path &&
                    existing.path != Scene3Path)
                {
                    wanted.Add(existing);
                }
            }

            EditorBuildSettings.scenes = wanted.ToArray();

            Debug.Log("[TRAIN SIM] Scene list now holds " + wanted.Count + " scenes.");
        }

        // ==========================================
        // TUNNEL
        // ==========================================

        // The bore runs along the track at x = 0, through the hill the pack put at z = 63.
        const float TunnelHalfWidth = 5f;
        const float TunnelStartZ = 44f;
        const float TunnelEndZ = 96f;

        /// <summary>
        /// Punches a hole through the terrain along the track so the hill becomes a tunnel the
        /// train can run through, instead of solid rock with the rails buried in it. The pack
        /// supplies the tunnel mouth as a prefab but never cut the ground away behind it.
        ///
        /// This edits stage.asset in place. It is idempotent, and revertible with git.
        /// </summary>
        [MenuItem("Tools/Train Sim/Carve Tunnel Through Terrain", priority = 21)]
        public static void CarveTunnel()
        {
            Terrain terrain = Object.FindFirstObjectByType<Terrain>();

            if (terrain == null)
            {
                // Nothing open, which is the normal case when this runs from the command line.
                EditorSceneManager.OpenScene(Scene1Path, OpenSceneMode.Single);
                terrain = Object.FindFirstObjectByType<Terrain>();
            }

            if (terrain == null || terrain.terrainData == null)
            {
                Debug.LogError("[TRAIN SIM] No terrain found.");
                return;
            }

            TerrainData data = terrain.terrainData;
            Vector3 origin = terrain.transform.position;
            Vector3 size = data.size;

            int res = data.holesResolution;
            bool[,] holes = data.GetHoles(0, 0, res, res);

            int cut = 0;

            for (int y = 0; y < res; y++)
            {
                // Holes are indexed [y, x], with y running along z.
                float worldZ = origin.z + (y / (float)(res - 1)) * size.z;

                if (worldZ < TunnelStartZ || worldZ > TunnelEndZ)
                {
                    continue;
                }

                for (int x = 0; x < res; x++)
                {
                    float worldX = origin.x + (x / (float)(res - 1)) * size.x;

                    if (Mathf.Abs(worldX) > TunnelHalfWidth)
                    {
                        continue;
                    }

                    if (holes[y, x])
                    {
                        holes[y, x] = false;      // false means hole
                        cut++;
                    }
                }
            }

            if (cut == 0)
            {
                Debug.Log("[TRAIN SIM] Tunnel already carved, nothing to do.");
                return;
            }

            Undo.RegisterCompleteObjectUndo(data, "Carve tunnel");
            data.SetHoles(0, 0, holes);
            EditorUtility.SetDirty(data);
            AssetDatabase.SaveAssets();

            Debug.Log(
                "[TRAIN SIM] Carved " + cut + " terrain cells into a tunnel between z " +
                TunnelStartZ + " and z " + TunnelEndZ + "."
            );
        }

        // ==========================================
        // GROUND NORTH OF THE TUNNEL (SCENE 3)
        // ==========================================

        const string StageTerrainPath =
            "Assets/pixel horror abandoned rural  train station/Terrain/stage.asset";

        const string NorthTerrainPath = "Assets/Scenes/Scene3_NorthTerrain.asset";

        // The pack terrain covers z -102.1 to 97.9. Scene 3 happens beyond that, where there was
        // nothing but sky under the rails, so this continues the ground for another 400 units.
        static readonly Vector3 NorthTerrainOrigin = new Vector3(-101f, 0f, 97.9f);
        static readonly Vector3 NorthTerrainSize = new Vector3(200f, 600f, 400f);
        const float HillFadeLength = 30f;       // the tunnel hill runs off the pack terrain's edge
        const float TreeClearance = 12f;        // keep the line clear so the second train is visible

        /// <summary>
        /// Builds the terrain scene 3 stands on and saves it as an asset for the generator to use.
        ///
        /// Its south edge copies the heights along the north edge of the pack terrain and eases
        /// them down to flat, so the tunnel hill ends in a slope instead of a cliff with a gap
        /// under it, and the tunnel cut carries on through that slope. The ground cover, trees
        /// and grass use the pack's own layers and prototypes at about the pack's tree density.
        ///
        /// Deterministic: a fixed seed, so rebuilding it gives the same forest.
        /// </summary>
        [MenuItem("Tools/Train Sim/Build Scene 3 Ground", priority = 23)]
        public static void BuildNorthTerrain()
        {
            TerrainData stage = AssetDatabase.LoadAssetAtPath<TerrainData>(StageTerrainPath);

            if (stage == null)
            {
                Debug.LogError("[TRAIN SIM] Cannot find " + StageTerrainPath);
                return;
            }

            var data = new TerrainData();
            data.heightmapResolution = 513;
            data.size = NorthTerrainSize;
            data.alphamapResolution = 512;
            data.SetDetailResolution(256, 32);

            int res = data.heightmapResolution;
            var heights = new float[res, res];
            var holes = new bool[res - 1, res - 1];
            var random = new System.Random(20260917);

            for (int zi = 0; zi < res; zi++)
            {
                float worldZ = NorthTerrainOrigin.z + zi / (float)(res - 1) * NorthTerrainSize.z;
                float fade = 1f - Mathf.SmoothStep(0f, 1f, (worldZ - NorthTerrainOrigin.z) / HillFadeLength);

                for (int xi = 0; xi < res; xi++)
                {
                    float u = xi / (float)(res - 1);
                    float worldX = NorthTerrainOrigin.x + u * NorthTerrainSize.x;

                    // The pack terrain's own height along its north edge, carried on and eased out.
                    float edge = stage.GetInterpolatedHeight(u, 1f);

                    // Low rolling ground well away from the line, so the far side is not a table top.
                    float away = Mathf.SmoothStep(0f, 1f, Mathf.InverseLerp(35f, 75f, Mathf.Abs(worldX)));
                    float rolling = Mathf.PerlinNoise(worldX * 0.018f + 3.7f, worldZ * 0.018f + 1.3f) * 16f * away;

                    heights[zi, xi] = (edge * fade + rolling) / NorthTerrainSize.y;
                }
            }

            data.SetHeights(0, 0, heights);

            // Carry the tunnel cut through the part of the hill that spills onto this terrain.
            for (int y = 0; y < res - 1; y++)
            {
                float worldZ = NorthTerrainOrigin.z + y / (float)(res - 2) * NorthTerrainSize.z;

                for (int x = 0; x < res - 1; x++)
                {
                    float worldX = NorthTerrainOrigin.x + x / (float)(res - 2) * NorthTerrainSize.x;
                    bool inCut = Mathf.Abs(worldX) <= TunnelHalfWidth &&
                                 worldZ <= NorthTerrainOrigin.z + HillFadeLength;

                    holes[y, x] = !inCut;   // true means solid ground
                }
            }

            data.SetHoles(0, 0, holes);

            // Ground cover: grass, with dirt along the line like the station end.
            data.terrainLayers = stage.terrainLayers;
            int alphaRes = data.alphamapResolution;
            int layers = data.terrainLayers.Length;
            int grass = 0;
            int dirt = Mathf.Min(2, layers - 1);
            var alphas = new float[alphaRes, alphaRes, layers];

            for (int y = 0; y < alphaRes; y++)
            {
                for (int x = 0; x < alphaRes; x++)
                {
                    float worldX = NorthTerrainOrigin.x + x / (float)(alphaRes - 1) * NorthTerrainSize.x;
                    float dirtAmount = 1f - Mathf.SmoothStep(0f, 1f, Mathf.InverseLerp(9f, 16f, Mathf.Abs(worldX)));

                    alphas[y, x, grass] = 1f - dirtAmount;
                    alphas[y, x, dirt] += dirtAmount;
                }
            }

            data.SetAlphamaps(0, 0, alphas);

            // Trees on a jittered grid at roughly the pack's density, kept off the line.
            data.treePrototypes = stage.treePrototypes;
            var trees = new List<TreeInstance>();
            const float spacing = 5.2f;

            for (float z = NorthTerrainOrigin.z + 2f; z < NorthTerrainOrigin.z + NorthTerrainSize.z - 2f; z += spacing)
            {
                for (float x = NorthTerrainOrigin.x + 2f; x < NorthTerrainOrigin.x + NorthTerrainSize.x - 2f; x += spacing)
                {
                    float px = x + (float)(random.NextDouble() - 0.5) * spacing * 0.9f;
                    float pz = z + (float)(random.NextDouble() - 0.5) * spacing * 0.9f;
                    int prototype = random.Next(data.treePrototypes.Length);
                    float scale = 0.8f + (float)random.NextDouble() * 0.45f;
                    float rotation = (float)random.NextDouble() * Mathf.PI * 2f;
                    bool keep = random.NextDouble() < 0.85;

                    if (!keep || Mathf.Abs(px) < TreeClearance)
                    {
                        continue;
                    }

                    float nx = (px - NorthTerrainOrigin.x) / NorthTerrainSize.x;
                    float nz = (pz - NorthTerrainOrigin.z) / NorthTerrainSize.z;

                    trees.Add(new TreeInstance
                    {
                        position = new Vector3(nx, data.GetInterpolatedHeight(nx, nz) / NorthTerrainSize.y, nz),
                        prototypeIndex = prototype,
                        widthScale = scale,
                        heightScale = scale,
                        rotation = rotation,
                        color = Color.white,
                        lightmapColor = Color.white
                    });
                }
            }

            data.SetTreeInstances(trees.ToArray(), true);

            // Grass clumps in scattered patches, off the ballast.
            data.detailPrototypes = stage.detailPrototypes;

            if (data.detailPrototypes.Length > 0)
            {
                int detailRes = data.detailResolution;
                var detail = new int[detailRes, detailRes];

                for (int y = 0; y < detailRes; y++)
                {
                    for (int x = 0; x < detailRes; x++)
                    {
                        float worldX = NorthTerrainOrigin.x + x / (float)(detailRes - 1) * NorthTerrainSize.x;
                        float patch = Mathf.PerlinNoise(x * 0.09f + 11f, y * 0.09f + 5f);

                        if (Mathf.Abs(worldX) > 8f && patch > 0.62f)
                        {
                            detail[y, x] = 1 + random.Next(3);
                        }
                    }
                }

                data.SetDetailLayer(0, 0, 0, detail);
            }

            AssetDatabase.DeleteAsset(NorthTerrainPath);
            AssetDatabase.CreateAsset(data, NorthTerrainPath);
            AssetDatabase.SaveAssets();

            Debug.Log(
                "[TRAIN SIM] Built " + NorthTerrainPath + " with " + trees.Count + " trees, " +
                "from z " + NorthTerrainOrigin.z + " to z " + (NorthTerrainOrigin.z + NorthTerrainSize.z) + "."
            );
        }

        // ==========================================
        // PASSENGER MODEL
        // ==========================================

        const string PassengerModelPath = "Assets/Passengers/Louise@Walking.fbx";
        const string PassengerControllerPath = "Assets/Passengers/Passenger.controller";
        const string PassengerPrefabPath = "Assets/Passengers/Passenger.prefab";

        /// <summary>
        /// Turns the downloaded Mixamo character into something the generator can drop into a
        /// scene: humanoid rig, a looping walk clip, an animator controller that plays it, and a
        /// prefab with PassengerWalker already on it.
        ///
        /// The clip was exported In Place, so it has no root motion and PassengerWalker keeps
        /// full control of where the figure actually goes.
        /// </summary>
        [MenuItem("Tools/Train Sim/Set Up Passenger Model", priority = 22)]
        public static void SetUpPassengerModel()
        {
            ModelImporter importer = AssetImporter.GetAtPath(PassengerModelPath) as ModelImporter;

            if (importer == null)
            {
                Debug.LogError("[TRAIN SIM] No model at " + PassengerModelPath);
                return;
            }

            importer.animationType = ModelImporterAnimationType.Human;
            importer.importAnimation = true;

            ModelImporterClipAnimation[] clips = importer.defaultClipAnimations;

            if (clips.Length > 0)
            {
                clips[0].name = "Walk";
                clips[0].loopTime = true;
                importer.clipAnimations = clips;
            }

            importer.SaveAndReimport();

            AnimationClip walk = null;

            foreach (Object o in AssetDatabase.LoadAllAssetsAtPath(PassengerModelPath))
            {
                AnimationClip c = o as AnimationClip;

                if (c != null && !c.name.StartsWith("__"))
                {
                    walk = c;
                }
            }

            if (walk == null)
            {
                Debug.LogError("[TRAIN SIM] No walk clip found inside " + PassengerModelPath);
                return;
            }

            AnimatorController controller =
                AnimatorController.CreateAnimatorControllerAtPathWithClip(
                    PassengerControllerPath, walk);

            GameObject model = AssetDatabase.LoadAssetAtPath<GameObject>(PassengerModelPath);
            GameObject instance = (GameObject)PrefabUtility.InstantiatePrefab(model);
            instance.name = "Passenger";

            Animator animator = instance.GetComponent<Animator>();

            if (animator == null)
            {
                animator = instance.AddComponent<Animator>();
            }

            animator.runtimeAnimatorController = controller;
            animator.applyRootMotion = false;

            // The clip drives the legs now, so the hand rolled bone swing is off.
            PassengerWalker walker = instance.AddComponent<PassengerWalker>();
            walker.enableBoneWalk = false;

            PrefabUtility.SaveAsPrefabAsset(instance, PassengerPrefabPath);
            Object.DestroyImmediate(instance);

            AssetDatabase.SaveAssets();

            Debug.Log(
                "[TRAIN SIM] Passenger prefab ready at " + PassengerPrefabPath +
                " using clip " + walk.name + "."
            );
        }

        // ==========================================
        // BUILD
        // ==========================================

        const string BuildDir = "Build/TrainSim";

        /// <summary>
        /// Builds a standalone Windows player so the whole thing can be run by double clicking one
        /// file, with no Unity and no setup. Scene 1 is first in the list, so the player boots
        /// straight into the run in and loads scene 2 itself.
        /// </summary>
        [MenuItem("Tools/Train Sim/Build Windows Player", priority = 40)]
        public static void BuildWindowsPlayer()
        {
            Directory.CreateDirectory(BuildDir);

            BuildPlayerOptions options = new BuildPlayerOptions();

            // Order matters: index 0 is what the player opens with.
            options.scenes = new[] { Scene1Path, Scene2Path, Scene3Path };
            options.locationPathName = BuildDir + "/TrainSim.exe";
            options.target = BuildTarget.StandaloneWindows64;
            options.options = BuildOptions.None;

            BuildReport report = BuildPipeline.BuildPlayer(options);

            if (report.summary.result == BuildResult.Succeeded)
            {
                Debug.Log(
                    "[BUILD] Player written to " + BuildDir + "/TrainSim.exe (" +
                    (report.summary.totalSize / (1024 * 1024)) + " MB)."
                );
            }
            else
            {
                Debug.LogError(
                    "[BUILD] Player build " + report.summary.result +
                    " with " + report.summary.totalErrors + " errors."
                );
            }
        }

        // ==========================================
        // MEASURING
        // ==========================================

        /// <summary>
        /// Prints the real mesh bounds behind the numbers at the top of the generator. Run this
        /// when something looks like it is floating or sunk, then correct the constants in
        /// Tools/generate_scenes.py rather than dragging objects around.
        /// </summary>
        [MenuItem("Tools/Train Sim/Probe Layout", priority = 20)]
        public static void Probe()
        {
            var sb = new System.Text.StringBuilder();
            sb.AppendLine("===== LAYOUT PROBE =====");

            ProbePrefab(sb, TrainPrefabPath);
            ProbePrefab(sb, RailPrefabPath);
            ProbePrefab(sb, PassengerModelPath);
            ProbePrefab(sb, HitogatasModelPath);

            ProbeTerrainAndPlatforms(sb);

            Debug.Log(sb.ToString());
        }

        static void ProbePrefab(System.Text.StringBuilder sb, string path)
        {
            GameObject prefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);

            if (prefab == null)
            {
                sb.AppendLine("MISSING: " + path);
                return;
            }

            GameObject instance = (GameObject)PrefabUtility.InstantiatePrefab(prefab);
            instance.transform.position = Vector3.zero;
            instance.transform.rotation = Quaternion.identity;

            Bounds bounds = new Bounds(Vector3.zero, Vector3.zero);
            bool first = true;

            foreach (Renderer renderer in instance.GetComponentsInChildren<Renderer>())
            {
                if (first)
                {
                    bounds = renderer.bounds;
                    first = false;
                }
                else
                {
                    bounds.Encapsulate(renderer.bounds);
                }
            }

            sb.AppendLine(System.IO.Path.GetFileNameWithoutExtension(path));
            sb.AppendLine("   size " + bounds.size + "   min " + bounds.min + "   max " + bounds.max);

            Object.DestroyImmediate(instance);
        }

        /// <summary>
        /// The terrain extent matters: the train starts at z = -95 and must not run off the edge
        /// of the ground. Platform surface height decides where the passengers stand.
        /// </summary>
        static void ProbeTerrainAndPlatforms(System.Text.StringBuilder sb)
        {
            Scene scene = EditorSceneManager.OpenScene(StationScenePath, OpenSceneMode.Additive);

            float platformTop = float.MinValue;
            float platformMinX = float.MaxValue, platformMaxX = float.MinValue;
            float platformMinZ = float.MaxValue, platformMaxZ = float.MinValue;

            foreach (GameObject root in scene.GetRootGameObjects())
            {
                Terrain terrain = root.GetComponent<Terrain>();

                if (terrain != null && terrain.terrainData != null)
                {
                    Vector3 size = terrain.terrainData.size;
                    Vector3 origin = root.transform.position;

                    sb.AppendLine("Terrain at " + origin + " size " + size);
                    sb.AppendLine("   covers x " + origin.x + " to " + (origin.x + size.x));
                    sb.AppendLine("   covers z " + origin.z + " to " + (origin.z + size.z));
                }

                if (!root.name.StartsWith("cement platform"))
                {
                    continue;
                }

                foreach (Renderer renderer in root.GetComponentsInChildren<Renderer>())
                {
                    // The west platform is the one the passengers board from.
                    if (renderer.bounds.center.x >= 0f)
                    {
                        continue;
                    }

                    if (renderer.bounds.max.y > platformTop)
                    {
                        platformTop = renderer.bounds.max.y;
                    }

                    platformMinX = Mathf.Min(platformMinX, renderer.bounds.min.x);
                    platformMaxX = Mathf.Max(platformMaxX, renderer.bounds.max.x);
                    platformMinZ = Mathf.Min(platformMinZ, renderer.bounds.min.z);
                    platformMaxZ = Mathf.Max(platformMaxZ, renderer.bounds.max.z);
                }
            }

            sb.AppendLine("west platform deck");
            sb.AppendLine("   surface y = " + platformTop);
            sb.AppendLine("   x from " + platformMinX + " to " + platformMaxX);
            sb.AppendLine("   z from " + platformMinZ + " to " + platformMaxZ);
            sb.AppendLine("   train carriage side sits at x = -3.73, so the gap to step over is "
                          + (-3.73f - platformMaxX));

            EditorSceneManager.CloseScene(scene, true);
        }
    }
}
